name: Deploy to Google

# Run this workflow every time a new commit pushed to your repository
#'on': push
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./functions

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install libraries
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: install firebase
      run: npm i firebase-tools -g  
    - name: deploy
      #run: firebase deploy --only functions:helloWorldHarshita --token '1//0gGpD-4SraNXaCgYIARAAGBASNwF-L9Iri1dUE-TslTR4cUrUkr4A1jf83uRUq1G3noVOxUiQqh54Zovgo3pfQnst3XNgX6ZlNW8'
      run: npx firebase-tools deploy --only functions:helloWorldHarshita --token "${{env.FIREBASE_TOKEN}}"
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CAREAR_PLAYGROUND }}
