name: Deploy to Google	
		
# Run this workflow every time a new commit pushed to your repository
#'on': push
'on': workflow_dispatch
		
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./functions

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install libraries
      run: npm install
      working-directory: ${{env.working-directory}}
   # - name: install firebase
   #   run: npm i firebase-tools -g  
    - name: deploy
      uses: w9jds/firebase-action@master
      with: 
           args: deploy --only functions:helloWorldHarshita
      env:
           GCP_SA_KEY: ${{ secrets.FIREBASE_CAREAR_HYPERSPACE }}

